server: 
  port: 8083

spring: 
  http: 
    charset: UTF-8
    enabled: true
    force: true
    mail: 
        default-encoding: UTF-8
    messages: 
        encoding: UTF-8

casServerUrlPrefix: https://cas.example.org:8443/cas
cas: 
  prefixUrl: https://cas.example.org:8443/cas
  loginUrl: ${cas.prefixUrl}/login
  logoutUrl: ${cas.prefixUrl}/logout
  serviceUrl: http://cas.client.com:${server.port}
  callbackUrl: ${cas.serviceUrl}/callback
jwt:
  salt: cas

debug: true


